-- MySQL Script generated by MySQL Workbench
-- Thu Nov  9 08:42:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema staff_administration
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `staff_administration` ;

-- -----------------------------------------------------
-- Schema staff_administration
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `staff_administration` DEFAULT CHARACTER SET utf8 ;
USE `staff_administration` ;

-- -----------------------------------------------------
-- Table `staff_administration`.`computer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff_administration`.`computer` (
  `id_service_tag` VARCHAR(45) NOT NULL,
  `hostname` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `mouse` VARCHAR(45) NOT NULL,
  `keyboard` VARCHAR(45) NOT NULL,
  `charger` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_service_tag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staff_administration`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff_administration`.`employees` (
  `staff_num` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `possition` VARCHAR(45) NOT NULL,
  `type_em` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `supervisor_name` VARCHAR(45) NOT NULL,
  `salary` FLOAT NOT NULL,
  `birthday` DATE NOT NULL,
  `program` VARCHAR(10) NOT NULL,
  `computer` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(4) NOT NULL,
  `office` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`staff_num`),
  CONSTRAINT `fk_employees_computer1`
    FOREIGN KEY (`computer`)
    REFERENCES `staff_administration`.`computer` (`id_service_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `staff_num_UNIQUE` ON `staff_administration`.`employees` (`staff_num` ASC) VISIBLE;

CREATE INDEX `fk_employees_computer1_idx` ON `staff_administration`.`employees` (`computer` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `staff_administration`.`monitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff_administration`.`monitor` (
  `idmonitor` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `plg` FLOAT NOT NULL,
  `computer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmonitor`),
  CONSTRAINT `fk_monitor_computer1`
    FOREIGN KEY (`computer`)
    REFERENCES `staff_administration`.`computer` (`id_service_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_monitor_computer1_idx` ON `staff_administration`.`monitor` (`computer` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
